#Get your ip from http://www.ipchicken.com
Ip: 00.00.000.00

#Get your UUID at https://mcuuid.net/
#Do not leave this blank, it will allow you to login no matter the case
UUID: g5971935-ffaf-41d5-b812-054f0dd0cfc4

#Your Player Name goes here, Im sure you know this one.. :P
Player: SpicyChicken